name = "PenguinSolverCore"
uuid = "8f14e45f-7d0b-4a6b-9c1e-2f3d4b5a6c7d"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[extensions]
PenguinSolverCoreSciMLBaseExt = "SciMLBase"

[compat]
LinearAlgebra = "1.11.0"
SciMLBase = "1, 2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
